name = "u2-public-transportation"
main = "worker.js"
compatibility_date = "2024-09-23"

[triggers]
crons = ["* * * * *"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[durable_objects]
bindings = [
  { name = "TRANSIT_STATE", class_name = "TransitState" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TransitState"]
